/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#faf9f6",
        "on-tertiary-fixed-variant": "#005313",
        "tertiary-fixed": "#94f990",
        "primary-fixed-dim": "#ffb68d",
        "inverse-on-surface": "#f2f1ee",
        "surface": "#faf9f6",
        "surface-container": "#efeeeb",
        "tertiary-container": "#5cbf5e",
        "on-tertiary-fixed": "#002204",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad7",
        "outline": "#897266",
        "error-container": "#ffdad6",
        "surface-container-low": "#f4f3f1",
        "on-secondary-fixed": "#001e2f",
        "surface-variant": "#e3e2e0",
        "on-error": "#ffffff",
        "on-tertiary-container": "#004a10",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#c9e6ff",
        "on-surface": "#1a1c1a",
        "on-primary-fixed": "#331200",
        "outline-variant": "#ddc1b3",
        "secondary-container": "#91d0fe",
        "secondary-fixed-dim": "#8fcefb",
        "inverse-primary": "#ffb68d",
        "on-primary-container": "#6a2d00",
        "inverse-surface": "#2f312f",
        "on-tertiary": "#ffffff",
        "surface-tint": "#9b4500",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#763300",
        "on-background": "#1a1c1a",
        "background": "#faf9f6",
        "tertiary-fixed-dim": "#78dc77",
        "primary-container": "#ff8c42",
        "primary-fixed": "#ffdbc9",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#006e1c",
        "primary": "#9b4500",
        "on-surface-variant": "#564338",
        "error": "#ba1a1a",
        "on-secondary-container": "#015a82",
        "secondary": "#19648d"
      },
      fontFamily: {
        "headline": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "body": ["var(--font-be-vietnam-pro)", "sans-serif"],
        "label": ["var(--font-plus-jakarta-sans)", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
